from models.character_models import ArmorModel


armors_table = {
    'Naked': (
        0,
    ArmorModel(
        armor_type='Naked',
        body_locations=[],
        weight=0,
        cab_reduction=0,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=0,
    ),
    ),
    'Arming Cap': (
         10,
    ArmorModel(
        armor_type='Arming Cap',
        body_locations=['head'],
        weight=0,
        cab_reduction=1,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=2,
    ),
    ),
    'Articulated Arms': (
         1800,
    ArmorModel(
        armor_type='Articulated Arms',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=2,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-1,
        modifer_to_hide=-2,
        modifer_to_silence=-2,
        ip=20,
    ),
    ),
    'Articulated Legs': (
         6500,
    ArmorModel(
        armor_type='Articulated Legs',
        body_locations=['left_foot', 'right_foot', 'lower_left_leg', 'lower_right_leg', 'upper_left_leg', 'upper_right_leg'],
        weight=12,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-2,
        modifer_to_hide=-2,
        modifer_to_silence=-3,
        ip=20,
    ),
    ),
    'Banded Mail': (
         5000,
    ArmorModel(
        armor_type='Banded Mail',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg'],
        weight=50,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-4,
        modifer_to_hide=-6,
        modifer_to_silence=-8,
        ip=10,
    ),
    ),
    'Boots, Calf': (
         20,
    ArmorModel(
        armor_type='Boots, Calf',
        body_locations=['left_foot', 'right_foot', 'lower_left_leg', 'lower_right_leg'],
        weight=3,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=3,
    ),
    ),
    'Boots, Knee': (
         30,
    ArmorModel(
        armor_type='Boots, Knee',
        body_locations=['left_foot', 'right_foot', 'lower_left_leg', 'lower_right_leg', 'upper_left_leg', 'upper_right_leg'],
        weight=4,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=4,
    ),
    ),
    'Boots, Thigh': (
         40,
    ArmorModel(
        armor_type='Boots, Thigh',
        body_locations=['left_foot', 'right_foot', 'lower_left_leg', 'lower_right_leg', 'upper_left_leg', 'upper_right_leg'],
        weight=5,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=5,
    ),
    ),
    'Bracers, Leather': (
         10,
    ArmorModel(
        armor_type='Bracers, Leather',
        body_locations=['lower_left_arm', 'lower_right_arm'],
        weight=0,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=4,
    ),
    ),
    'Bracers, Steel': (
         30,
    ArmorModel(
        armor_type='Bracers, Steel',
        body_locations=['lower_left_arm', 'lower_right_arm'],
        weight=1,
        cab_reduction=18,
        cah_reduction=14,
        cap_reduction=14,
        cas_reduction=14,
        agility_loss=0,
        modifer_to_hide=-2,
        modifer_to_silence=0,
        ip=8,
    ),
    ),
    'Breastplate and Backplate': (
         4500,
    ArmorModel(
        armor_type='Breastplate and Backplate',
        body_locations=['lower_torso', 'upper_torso'],
        weight=9,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-2,
        modifer_to_hide=-3,
        modifer_to_silence=-2,
        ip=25,
    ),
    ),
    'Brigandine': (
         200,
    ArmorModel(
        armor_type='Brigandine',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm'],
        weight=25,
        cab_reduction=12,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-6,
        modifer_to_hide=0,
        modifer_to_silence=-2,
        ip=20,
    ),
    ),
    'Chainmail Chausses (4-in-1)': (
         500,
    ArmorModel(
        armor_type='Chainmail Chausses (4-in-1)',
        body_locations=['left_foot', 'right_foot', 'lower_left_leg', 'lower_right_leg', 'upper_left_leg', 'upper_right_leg'],
        weight=13,
        cab_reduction=12,
        cah_reduction=10,
        cap_reduction=8,
        cas_reduction=8,
        agility_loss=-1,
        modifer_to_hide=-3,
        modifer_to_silence=-4,
        ip=5,
    ),
    ),
    'Chainmail Chausses (6-in-1)': (
         750,
    ArmorModel(
        armor_type='Chainmail Chausses (6-in-1)',
        body_locations=['left_foot', 'right_foot', 'lower_left_leg', 'lower_right_leg', 'upper_left_leg', 'upper_right_leg'],
        weight=19,
        cab_reduction=18,
        cah_reduction=12,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-2,
        modifer_to_hide=-3,
        modifer_to_silence=-4,
        ip=8,
    ),
    ),
    'Chainmail Coif (4-in-1)': (
         200,
    ArmorModel(
        armor_type='Chainmail Coif (4-in-1)',
        body_locations=['head', 'face'],
        weight=5,
        cab_reduction=12,
        cah_reduction=10,
        cap_reduction=8,
        cas_reduction=8,
        agility_loss=0,
        modifer_to_hide=-2,
        modifer_to_silence=-3,
        ip=5,
    ),
    ),
    'Chainmail Coif (6-in-1)': (
         300,
    ArmorModel(
        armor_type='Chainmail Coif (6-in-1)',
        body_locations=['head', 'face'],
        weight=8,
        cab_reduction=18,
        cah_reduction=12,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-2,
        modifer_to_silence=-3,
        ip=8,
    ),
    ),
    'Chainmail Hauberk (4-in-1)': (
         1000,
    ArmorModel(
        armor_type='Chainmail Hauberk (4-in-1)',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=30,
        cab_reduction=12,
        cah_reduction=10,
        cap_reduction=8,
        cas_reduction=8,
        agility_loss=-2,
        modifer_to_hide=-3,
        modifer_to_silence=-4,
        ip=10,
    ),
    ),
    'Chainmail Hauberk (6-in-1)': (
         1500,
    ArmorModel(
        armor_type='Chainmail Hauberk (6-in-1)',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=45,
        cab_reduction=18,
        cah_reduction=12,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-3,
        modifer_to_hide=-3,
        modifer_to_silence=-4,
        ip=15,
    ),
    ),
    'Clothing': (
         20,
    ArmorModel(
        armor_type='Clothing',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=3,
        cab_reduction=1,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=-1,
        ip=2,
    ),
    ),
    'Gambeson': (
         10,
    ArmorModel(
        armor_type='Gambeson',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=2,
        cab_reduction=3,
        cah_reduction=3,
        cap_reduction=2,
        cas_reduction=2,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=-1,
        ip=5,
    ),
    ),
    'Gauntlets, Bell-cuffed': (
         1000,
    ArmorModel(
        armor_type='Gauntlets, Bell-cuffed',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm'],
        weight=1,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=-2,
        ip=10,
    ),
    ),
    'Gauntlets, Clamshell': (
         700,
    ArmorModel(
        armor_type='Gauntlets, Clamshell',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm'],
        weight=1,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=-2,
        ip=15,
    ),
    ),
    'Gloves, Leather': (
         10,
    ArmorModel(
        armor_type='Gloves, Leather',
        body_locations=['left_hand', 'right_hand'],
        weight=1,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=3,
    ),
    ),
    'Gorget': (
         900,
    ArmorModel(
        armor_type='Gorget',
        body_locations=['upper_torso'],
        weight=1,
        cab_reduction=2,
        cah_reduction=1,
        cap_reduction=1,
        cas_reduction=1,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=-3,
        ip=15,
    ),
    ),
    'Greaves': (
         1800,
    ArmorModel(
        armor_type='Greaves',
        body_locations=['lower_left_leg', 'lower_right_leg'],
        weight=3,
        cab_reduction=18,
        cah_reduction=14,
        cap_reduction=14,
        cas_reduction=14,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=20,
    ),
    ),
    'Lamellar': (
         450,
    ArmorModel(
        armor_type='Lamellar',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg'],
        weight=30,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-8,
        modifer_to_hide=-7,
        modifer_to_silence=-8,
        ip=15,
    ),
    ),
    'Leather': (
         70,
    ArmorModel(
        armor_type='Leather',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=7,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=-1,
        modifer_to_hide=0,
        modifer_to_silence=-2,
        ip=5,
    ),
    ),
    'Leather, Studded': (
         50,
    ArmorModel(
        armor_type='Leather, Studded',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=5,
        cab_reduction=5,
        cah_reduction=5,
        cap_reduction=3,
        cas_reduction=3,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=-1,
        ip=5,
    ),
    ),
    'Muscle Mail': (
         6000,
    ArmorModel(
        armor_type='Muscle Mail',
        body_locations=['lower_torso', 'upper_torso'],
        weight=12,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-2,
        modifer_to_hide=-2,
        modifer_to_silence=-2,
        ip=25,
    ),
    ),
    'Pauldrons': (
         1000,
    ArmorModel(
        armor_type='Pauldrons',
        body_locations=['upper_left_arm', 'upper_right_arm'],
        weight=1,
        cab_reduction=3,
        cah_reduction=2,
        cap_reduction=2,
        cas_reduction=2,
        agility_loss=-1,
        modifer_to_hide=-1,
        modifer_to_silence=-3,
        ip=15,
    ),
    ),
    'Sabatons': (
         1000,
    ArmorModel(
        armor_type='Sabatons',
        body_locations=['left_foot', 'right_foot'],
        weight=1,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-1,
        modifer_to_hide=-1,
        modifer_to_silence=-3,
        ip=20,
    ),
    ),
    'Sandals': (
         4,
    ArmorModel(
        armor_type='Sandals',
        body_locations=['left_foot', 'right_foot'],
        weight=1,
        cab_reduction=1,
        cah_reduction=1,
        cap_reduction=1,
        cas_reduction=1,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=2,
    ),
    ),
    'Scalemail, Brass': (
         340,
    ArmorModel(
        armor_type='Scalemail, Brass',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=38,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=8,
        agility_loss=-5,
        modifer_to_hide=-7,
        modifer_to_silence=-8,
        ip=15,
    ),
    ),
    'Scalemail, Brass and Iron': (
         350,
    ArmorModel(
        armor_type='Scalemail, Brass and Iron',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=37,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=8,
        agility_loss=-5,
        modifer_to_hide=-7,
        modifer_to_silence=-8,
        ip=15,
    ),
    ),
    'Scalemail, Bronze': (
         360,
    ArmorModel(
        armor_type='Scalemail, Bronze',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=36,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=8,
        agility_loss=-5,
        modifer_to_hide=-7,
        modifer_to_silence=-8,
        ip=15,
    ),
    ),
    'Scalemail, Iron': (
         380,
    ArmorModel(
        armor_type='Scalemail, Iron',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=35,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=8,
        agility_loss=-5,
        modifer_to_hide=-7,
        modifer_to_silence=-8,
        ip=15,
    ),
    ),
    'Scalemail, Steel': (
         400,
    ArmorModel(
        armor_type='Scalemail, Steel',
        body_locations=['lower_torso', 'upper_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm'],
        weight=35,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=8,
        agility_loss=-5,
        modifer_to_hide=-7,
        modifer_to_silence=-8,
        ip=15,
    ),
    ),
    'Segmented': (
         500,
    ArmorModel(
        armor_type='Segmented',
        body_locations=['head', 'face', 'upper_torso', 'lower_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'left_hand', 'right_hand', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'left_foot', 'right_foot'],
        weight=35,
        cab_reduction=16,
        cah_reduction=12,
        cap_reduction=12,
        cas_reduction=12,
        agility_loss=-4,
        modifer_to_hide=-7,
        modifer_to_silence=-6,
        ip=20,
    ),
    ),
    'Shoes': (
         10,
    ArmorModel(
        armor_type='Shoes',
        body_locations=['left_foot', 'right_foot'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=4,
    ),
    ),
    'Shoes, Clogs': (
         13,
    ArmorModel(
        armor_type='Shoes, Clogs',
        body_locations=['left_foot', 'right_foot'],
        weight=4,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=5,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=6,
    ),
    ),
    'Shoes, Felt': (
         25,
    ArmorModel(
        armor_type='Shoes, Felt',
        body_locations=['left_foot', 'right_foot'],
        weight=2,
        cab_reduction=3,
        cah_reduction=3,
        cap_reduction=2,
        cas_reduction=2,
        agility_loss=0,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=3,
    ),
    ),
    'Helm, Conical': (
         100,
    ArmorModel(
        armor_type='Helm, Conical',
        body_locations=['head'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Helm, Conical w/cheek guards': (
         150,
    ArmorModel(
        armor_type='Helm, Conical w/cheek guards',
        body_locations=['head', 'face'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Helm, Conical w/face guard': (
         150,
    ArmorModel(
        armor_type='Helm, Conical w/face guard',
        body_locations=['head', 'face'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Helm, Conical w/nasal guard': (
         125,
    ArmorModel(
        armor_type='Helm, Conical w/nasal guard',
        body_locations=['head', 'face'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Helm, Gladiatorial': (
         600,
    ArmorModel(
        armor_type='Helm, Gladiatorial',
        body_locations=['head', 'face'],
        weight=4,
        cab_reduction=20,
        cah_reduction=13,
        cap_reduction=10,
        cas_reduction=15,
        agility_loss=-1,
        modifer_to_hide=-2,
        modifer_to_silence=-1,
        ip=20,
    ),
    ),
    'Helm, Great': (
         500,
    ArmorModel(
        armor_type='Helm, Great',
        body_locations=['head', 'face'],
        weight=3,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-1,
        modifer_to_hide=-2,
        modifer_to_silence=-1,
        ip=25,
    ),
    ),
    'Helm, Ribbed': (
         50,
    ArmorModel(
        armor_type='Helm, Ribbed',
        body_locations=['head'],
        weight=2,
        cab_reduction=7,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=3,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=5,
    ),
    ),
    'Helm, Spangen w/cheek guards': (
         200,
    ArmorModel(
        armor_type='Helm, Spangen w/cheek guards',
        body_locations=['head', 'face'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=15,
    ),
    ),
    'Helm, Spangen w/face guard': (
         200,
    ArmorModel(
        armor_type='Helm, Spangen w/face guard',
        body_locations=['head', 'face'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=15,
    ),
    ),
    'Helm, Spangen w/nasal guard': (
         175,
    ArmorModel(
        armor_type='Helm, Spangen w/nasal guard',
        body_locations=['head', 'face'],
        weight=2,
        cab_reduction=10,
        cah_reduction=5,
        cap_reduction=5,
        cas_reduction=10,
        agility_loss=0,
        modifer_to_hide=-1,
        modifer_to_silence=0,
        ip=15,
    ),
    ),
    'Buckler, Steel': (
         40,
    ArmorModel(
        armor_type='Buckler, Steel',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm'],
        weight=3,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-1,
        modifer_to_hide=-3,
        modifer_to_silence=0,
        ip=15,
    ),
    ),
    'Buckler, Wood': (
         20,
    ArmorModel(
        armor_type='Buckler, Wood',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm'],
        weight=2,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-1,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=5,
    ),
    ),
    'Shield, Body, Wood': (
         200,
    ArmorModel(
        armor_type='Shield, Body, Wood',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=6,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-15,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=15,
    ),
    ),
    'Shield, Kite, Wood': (
         60,
    ArmorModel(
        armor_type='Shield, Kite, Wood',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=3,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-2,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Shield, Heater, Steel': (
         100,
    ArmorModel(
        armor_type='Shield, Heater, Steel',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=7,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-4,
        modifer_to_hide=-4,
        modifer_to_silence=0,
        ip=25,
    ),
    ),
    'Shield, Heater, Wood': (
         70,
    ArmorModel(
        armor_type='Shield, Heater, Wood',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=3,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-2,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Shield, Round, Bronze': (
         200,
    ArmorModel(
        armor_type='Shield, Round, Bronze',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=10,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-8,
        modifer_to_hide=-2,
        modifer_to_silence=0,
        ip=30,
    ),
    ),
    'Shield, Round, Steel': (
         80,
    ArmorModel(
        armor_type='Shield, Round, Steel',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=6,
        cab_reduction=20,
        cah_reduction=15,
        cap_reduction=15,
        cas_reduction=15,
        agility_loss=-3,
        modifer_to_hide=-4,
        modifer_to_silence=0,
        ip=25,
    ),
    ),
    'Shield, Round, Wood': (
         50,
    ArmorModel(
        armor_type='Shield, Round, Wood',
        body_locations=['left_hand', 'right_hand', 'lower_left_arm', 'lower_right_arm', 'upper_left_arm', 'upper_right_arm'],
        weight=3,
        cab_reduction=15,
        cah_reduction=10,
        cap_reduction=10,
        cas_reduction=10,
        agility_loss=-2,
        modifer_to_hide=0,
        modifer_to_silence=0,
        ip=10,
    ),
    ),
    'Chainmail Suit (4-in-1)': (
         2000,
    ArmorModel(
        armor_type='Chainmail Suit (4-in-1)',
        body_locations=['head', 'face', 'upper_torso', 'lower_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'left_hand', 'right_hand', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'left_foot', 'right_foot'],
        weight=52,
        cab_reduction=0,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=-3,
        modifer_to_hide=-8,
        modifer_to_silence=-12,
        ip=0,
    ),
    ),
    'Chainmail Suit (6-in-1)': (
         3000,
    ArmorModel(
        armor_type='Chainmail Suit (6-in-1)',
        body_locations=['head', 'face', 'upper_torso', 'lower_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'left_hand', 'right_hand', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'left_foot', 'right_foot'],
        weight=78,
        cab_reduction=0,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=-5,
        modifer_to_hide=-8,
        modifer_to_silence=-12,
        ip=0,
    ),
    ),
    'Chainmail w/Breastplate': (
         6500,
    ArmorModel(
        armor_type='Chainmail w/Breastplate',
        body_locations=['head', 'face', 'upper_torso', 'lower_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'left_hand', 'right_hand', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'left_foot', 'right_foot'],
        weight=49,
        cab_reduction=0,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=-5,
        modifer_to_hide=-9,
        modifer_to_silence=-13,
        ip=0,
    ),
    ),
    'Platemail Suit': (
         20000,
    ArmorModel(
        armor_type='Platemail Suit',
        body_locations=['head', 'face', 'upper_torso', 'lower_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'left_hand', 'right_hand', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'left_foot', 'right_foot'],
        weight=70,
        cab_reduction=0,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=-12,
        modifer_to_hide=-12,
        modifer_to_silence=-28,
        ip=0,
    ),
    ),
    'Platemail Suit, Ceremonial': (
         1000000,
    ArmorModel(
        armor_type='Platemail Suit, Ceremonial',
        body_locations=['head', 'face', 'upper_torso', 'lower_torso', 'groin', 'upper_left_arm', 'upper_right_arm', 'lower_left_arm', 'lower_right_arm', 'left_hand', 'right_hand', 'upper_left_leg', 'upper_right_leg', 'lower_left_leg', 'lower_right_leg', 'left_foot', 'right_foot'],
        weight=65,
        cab_reduction=0,
        cah_reduction=0,
        cap_reduction=0,
        cas_reduction=0,
        agility_loss=-10,
        modifer_to_hide=-15,
        modifer_to_silence=-25,
        ip=0,
    ),
    ),
}
