from dice import d10, d20

ethicality_table = {
    1: "Unethical",
    2: "Unethical w/ Neutral",
    3: "Unethical w/ Neutral",
    4: "Neutral w/ Unethical",
    5: "Neutral w/ Unethical",
    6: "Neutral w/ Unethical",
    7: "Neutral",
    8: "Neutral",
    9: "Neutral",
    10: "Neutral",
    11: "Neutral",
    12: "Neutral",
    13: "Neutral",
    14: "Neutral",
    15: "Neutral w/ Ethical",
    16: "Neutral w/ Ethical",
    17: "Neutral w/ Ethical",
    18: "Ethical w/ Neutral",
    19: "Ethical w/ Neutral",
    20: "Ethical",
}

morality_table = {
    1: "Immoral",
    2: "Immoral w/ Neutral",
    3: "Immoral w/ Neutral",
    4: "Neutral w/ Immoral",
    5: "Neutral w/ Immoral",
    6: "Neutral w/ Immoral",
    7: "Neutral",
    8: "Neutral",
    9: "Neutral",
    10: "Neutral",
    11: "Neutral",
    12: "Neutral",
    13: "Neutral",
    14: "Neutral",
    15: "Neutral w/ Moral",
    16: "Neutral w/ Moral",
    17: "Neutral w/ Moral",
    18: "Moral w/ Neutral",
    19: "Moral w/ Neutral",
    20: "Moral",
}

#name, linear effects, percentage effects
mental_illness_table = {
    "1": ("Abasiophilia",None,[],[]),
    "2": ("Acrotomophilia",None,[],[]),
    "3-11": ("Anorexia Nervosa", None,[("melancholic", d20() + d20())], [("weight", 1.25), ("physical_fitness", 0.9),
                                                            ("strength", 0.75), ("bodily_attractiveness", 0.9),
                                                            ("health", 0.75), ("drive", 1.1)]),
    "12-50": ("Antisocial Personality Disorder", None, [("choleric", d20()+d20()+d20()), ("melancholic", d20()+d20())], []),
    "51": ("Autoabasiophilia",None,[],[]),
    "52-91": ("Avoidant Personality Disorder",None, [("sanguine", d20()+d20())],[]),
    "92-100": ("Bipolar Disorder (Manic-Depressive)",None, [("choleric", d20()+d20()), ("melancholic", d20()+d20())],[]),
    "101-120": ("Borderline Personality Disorder",None, [("melancholic", d20()+d20())],[]),
    "121-122": ("Callomania",None,[],[]),
    "123": ("Choreomania",None,[],[]),
    "124-128": ("Coprophilia",None, [("debauchery_value", 97)],[]),
    "129-133": ("Dementia",None, [],[("rhetorical", float(f"1.{(30+ d10()+d10()):02d}")), ("analytic", float(f"1.{(30+ d10()+d10()):02d}")), ("reflection", float(f"1.{(30+ d10()+d10()):02d}"))]),
    "134-140": ("Dependent Personality Disorder",None,[],[]),
    "141-145": ("Depersonalization Disorder",None,[],[]),
    "146-250": ("Depression", None,[("melancholic", d20()+d20()), ("sanguine", d20()+d20())],[]),
    "251-255": ("Dissociative Fugue",None,[],[]),
    "256-260": ("Dissociative Identity Disorder (Multiple Personality Disorder)",None,[],[]),
    "261-265": ("Eleutheromania",None,[],[]),
    "266-270": ("Egomania",None,[],[]),
    "271-275": ("Erotomania", None,[("debauchery_value", 5)],[]),
    "276-280": ("Erotophonophilia", None,[("debauchery_value", 25), ("choleric", d20()+d20())],[]),
    "281-285": ("Esthesiomania",None,[],[]),
    "286-300": ("Exhibitionism", None,[("debauchery_value", 5)],[]),
    "301-305": ("Formicophilia", None,[("debauchery_value", 100)],[]),
    "306-310": ("Frotteurism", None,[("debauchery_value", 5)],[]),
    "311-330": ("Generalized Anxiety Disorder",None,[],[]),
    "331-335": ("Histrionic Personality Disorder",None,[],[]),
    "336-340": ("Hypersomnia",None,[],[]),
    "341-345": ("Hypoxyphilia", None,[("debauchery_value", 25)],[]),
    "346-350": ("Intermittent Explosive Disorder",None,[],[]),
    "351-370": ("Kleptomania",None,[],[]),
    "371-390": ("Mania",None,[],[]),
    "391-395": ("Megalomania",None,[],[]),
    "396-400": ("Narcissistic Personality Disorder",None,[],[]),
    "401-405": ("Narratophilia", None,[("debauchery_value", 10)],[]),
    "406-410": ("Necrophilia", None,[("debauchery_value", 100)],[]),
    "411-420": ("Noctomania",None,[],[]),
    "421-450": ("Nymphomania", 'female',[("debauchery_value", 25)],[]),
    "451-460": ("Obsessive-Compulsive Disorder",None,[],[]),
    "461-470": ("Obsessive-Comp. Personality Disorder", None,[("choleric", d20()), ("melancholic", d20())],[]),
    "471-475": ("Oniomania",None,[],[]),
    "476-480": ("Onomatomania",None,[],[]),
    "481-500": ("Panic Disorder",None,[],[]),
    "501-550": ("Paranoia", None,[("sanguine", -1 *(d20()+d20()))],[]),
    "551-570": ("Paranoid Personality Disorder", None,[("sanguine", -1 *(d20()+d20())), ("choleric", d20()+d20())],[]),
    "571-590": ("Pathological Gambling",None,[],[]),
    "591-600": ("Pedophilia", None,[("debauchery_value", 25)],[]),
    "601-700": ("Phobia",None,[],[]),
    "701-710": ("Post-Traumatic Stress Disorder", None,[("sanguine", -1 *(d20()))],[]),
    "711-730": ("Psychosis",None,[],[]),
    "731-760": ("Pyromania",None,[],[]),
    "761-800": ("Raptophilia", None,[("debauchery_value", 50)],[]),
    "801-849": ("Satyromania", 'male',[("debauchery_value", 25)],[]),
    "850-864": ("Schizoid Personality Disorder", None,[("sanguine", -1 *(d20()+d20())), ("choleric", -1 * (d20()+d20())), ("melancholic", -1 *(d20()+d20())), ("phlegmatic", d20()+d20())],[]),
    "865-894": ("Schizophrenia",None,[],[]),
    "895-899": ("Scoptophilia", None,[("debauchery_value", 5)],[]),
    "900-924": ("Sexual Masochism", None,[("debauchery_value", 90)],[]),
    "925-949": ("Sexual Sadism", None,[("debauchery_value", 70), ("choleric", d20()+d20()), ("sanguine", -1*(d20()+d20()))],[]),
    "950-971": ("Sleepwalking Disorder",None,[],[]),
    "972-973": ("Somnophilia", None,[("debauchery_value", 25)],[]),
    "974-975": ("Trichotillomania",None,[],[]),
    "976-977": ("Urophilia", None,[("debauchery_value", 97)],[]),
    "978": ("Vaginismus", 'female',[("sanguine", -1*(d20()))],[]),
    "979": ("Vomerophilia", None,[("debauchery_value", 100)],[]),
    "980-989": ("Voyeurism", None,[("debauchery_value", 5)],[]),
    "990-998": ("Zoophilia", None,[("debauchery_value", 25)],[]),
}


def lookup_mental_illness(roll: int) -> str:
    for roll_key, illness in mental_illness_table.items():
        if "-" in roll_key:
            low, high = (int(part) for part in roll_key.split("-", 1))
            if low <= roll <= high:
                return illness
        elif roll == int(roll_key):
            return illness
    raise KeyError(f"No mental illness for roll {roll}")


male_debauchery_table = {
    1: "Refuse all sex",
    2: "Receive handjob",
    3: "Receive oral sex",
    4: "Give vaginal sex",
    5: "Give fingering",
    6: "Give fingering",
    7: "Give fingering",
    8: "Give fingering",
    9: "Give fingering",
    10: "Give fingering",
    11: "Give fingering",
    12: "Give fingering",
    13: "Give fingering",
    14: "Give fingering",
    15: "Give fingering",
    16: "Give fingering",
    17: "Give fingering",
    18: "Give fingering",
    19: "Give fingering",
    20: "Give fingering",
    21: "Give fingering",
    22: "Give fingering",
    23: "Give fingering",
    24: "Give fingering",
    25: "Give fingering",
    26: "Give oral sex",
    27: "Give oral sex",
    28: "Give oral sex",
    29: "Give oral sex",
    30: "Give oral sex",
    31: "Give oral sex",
    32: "Give oral sex",
    33: "Give oral sex",
    34: "Give oral sex",
    35: "Give oral sex",
    36: "Give oral sex",
    37: "Give oral sex",
    38: "Give oral sex",
    39: "Give oral sex",
    40: "Give oral sex",
    41: "Give oral sex",
    42: "Give oral sex",
    43: "Give oral sex",
    44: "Give oral sex",
    45: "Give oral sex",
    46: "Give oral sex",
    47: "Give oral sex",
    48: "Give oral sex",
    49: "Give oral sex",
    50: "Give oral sex",
    51: "Entertain multiple partners",
    52: "Entertain multiple partners",
    53: "Entertain multiple partners",
    54: "Entertain multiple partners",
    55: "Entertain multiple partners",
    56: "Entertain multiple partners",
    57: "Entertain multiple partners",
    58: "Entertain multiple partners",
    59: "Entertain multiple partners",
    60: "Entertain multiple partners",
    61: "Give anal sex",
    62: "Give anal sex",
    63: "Give anal sex",
    64: "Give anal sex",
    65: "Give anal sex",
    66: "Give anal sex",
    67: "Give anal sex",
    68: "Give anal sex",
    69: "Give anal sex",
    70: "Give anal sex",
    71: "Give pain",
    72: "Give pain",
    73: "Give pain",
    74: "Give pain",
    75: "Give pain",
    76: "Give pain",
    77: "Give pain",
    78: "Give pain",
    79: "Give pain",
    80: "Give pain",
    81: "Urinate on partner",
    82: "Urinate on partner",
    83: "Urinate on partner",
    84: "Urinate on partner",
    85: "Urinate on partner",
    86: "Urinate on partner",
    87: "Urinate on partner",
    88: "Be bound",
    89: "Be bound",
    90: "Be bound",
    91: "Receive pain",
    92: "Be urinated on",
    93: "Be urinated on",
    94: "Be urinated on",
    95: "Defecate on partner",
    96: "Defecate on partner",
    97: "Be defecated on",
    98: "Drink urine",
    99: "Eat defecation",
    100: "Do Anything"
}

female_debauchery_table = {
    1: "Refuse all sex",
    2: "Refuse all sex",
    3: "Refuse all sex",
    4: "Refuse all sex",
    5: "Refuse all sex",
    6: "Give handjob",
    7: "Give handjob",
    8: "Give handjob",
    9: "Give handjob",
    10: "Give handjob",
    11: "Give oral sex",
    12: "Give oral sex",
    13: "Give oral sex",
    14: "Give oral sex",
    15: "Give oral sex",
    16: "Give oral sex and swallow",
    17: "Give oral sex and swallow",
    18: "Give oral sex and swallow",
    19: "Give oral sex and swallow",
    20: "Give oral sex and swallow",
    21: "Recieve fingering",
    22: "Recieve fingering",
    23: "Recieve fingering",
    24: "Recieve fingering",
    25: "Recieve fingering",
    26: "Receive vaginal sex",
    27: "Receive vaginal sex",
    28: "Receive vaginal sex",
    29: "Receive vaginal sex",
    30: "Receive vaginal sex",
    31: "Receive vaginal sex",
    32: "Receive vaginal sex",
    33: "Receive vaginal sex",
    34: "Receive vaginal sex",
    35: "Receive vaginal sex",
    36: "Receive vaginal sex",
    37: "Receive vaginal sex",
    38: "Receive vaginal sex",
    39: "Receive vaginal sex",
    40: "Receive vaginal sex",
    41: "Receive vaginal sex",
    42: "Receive vaginal sex",
    43: "Receive vaginal sex",
    44: "Receive vaginal sex",
    45: "Receive vaginal sex",
    46: "Receive vaginal sex",
    47: "Receive vaginal sex",
    48: "Receive vaginal sex",
    49: "Receive vaginal sex",
    50: "Receive vaginal sex",
    51: "Receive vaginal sex",
    52: "Receive vaginal sex",
    53: "Receive vaginal sex",
    54: "Receive vaginal sex",
    55: "Receive vaginal sex",
    56: "Receive mammary sex",
    57: "Receive mammary sex",
    58: "Receive mammary sex",
    59: "Receive mammary sex",
    60: "Receive mammary sex",
    61: "Receive oral sex",
    62: "Receive oral sex",
    63: "Receive oral sex",
    64: "Receive oral sex",
    65: "Receive oral sex",
    66: "Entertain multiple partners",
    67: "Entertain multiple partners",
    68: "Entertain multiple partners",
    69: "Entertain multiple partners",
    70: "Entertain multiple partners",
    71: "Give pain",
    72: "Give pain",
    73: "Be bound",
    74: "Be bound",
    75: "Be bound",
    76: "Recieve anal sex",
    77: "Recieve anal sex",
    78: "Recieve anal sex",
    79: "Recieve anal sex",
    80: "Recieve anal sex",
    81: "Recieve anal sex",
    82: "Recieve anal sex",
    83: "Recieve anal sex",
    84: "Recieve anal sex",
    85: "Recieve anal sex",
    86: "Recieve anal sex",
    87: "Recieve anal sex",
    88: "Recieve anal sex",
    89: "Recieve anal sex",
    90: "Recieve anal sex",
    91: "Recieve anal sex",
    92: "Urinate on partner",
    93: "Urinate on partner",
    94: "Receive pain",
    95: "Be urinated on",
    96: "Defecate on partner",
    97: "Be defecated on",
    98: "Drink urine",
    99: "Eat defecation",
    100: "Do Anything"
}