from models.character_models import FatalModel, WeaponModel
from dice import d2, d4, d6, d8, d10, d12, d20
from math import floor

# -1 : strength /10
# -2 : strength /5
# -3 : strength /4
# -4 : strength /2
def update_weapon(character: FatalModel, weapon: WeaponModel):
    if weapon.weight_distribution == -1:
        weapon.weight_distribution = character.strength / 10
    elif weapon.weight_distribution == -2:
        weapon.weight_distribution = character.strength / 5
    elif weapon.weight_distribution == -3:
        weapon.weight_distribution = character.strength / 4
    elif weapon.weight_distribution == -4:
        weapon.weight_distribution = character.strength / 2

    if weapon.weapon_range == -1:
        weapon.weapon_range = character.strength / 10
    elif weapon.weapon_range == -2:
        weapon.weapon_range = character.strength / 5
    elif weapon.weapon_range == -3:
        weapon.weapon_range = character.strength / 4
    elif weapon.weapon_range == -4:
        weapon.weapon_range = character.strength / 2

    return weapon

weapons_table = [
    WeaponModel(
        weapon="Axe, Battle, Footman's (2H)(w/o back spike)",
        weapon_type='H:SA',
        size='M 48"',
        weight=4,
        weight_distribution=0.90,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=5,
        h=-10,
    ),
    WeaponModel(
        weapon="Axe, Battle, Horseman's (w/back spike)",
        weapon_type='H(S):SA',
        size='S 24"',
        weight=3,
        weight_distribution=0.85,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d12()+1,
        l=0,
        m=5,
        h=-15,
    ),
    WeaponModel(
        weapon='Axe, Hand (Hatchet) (also thrown)',
        weapon_type='H:A',
        size='T 15"',
        weight=2,
        weight_distribution=0.80,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d10(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Club',
        weapon_type='P:SA',
        size='S 24"',
        weight=2,
        weight_distribution=0.60,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d6()+d6(),
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon='Club, Great (2H)',
        weapon_type='P:S',
        size='M 36-48"',
        weight=4,
        weight_distribution=0.60,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d8()+d8()+d8(),
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon='Dagger (double-edged) (also thrown)',
        weapon_type='S:A',
        size='T 11-18"',
        weight=1,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10(),
        l=0,
        m=-5,
        h=-20,
    ),
    WeaponModel(
        weapon='Dagger, Dirk (single edge)',
        weapon_type='S:A',
        size='S 17-21"',
        weight=2,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d12(),
        l=0,
        m=-10,
        h=-25,
    ),
    WeaponModel(
        weapon='Dagger, Stiletto(triple edge)',
        weapon_type='S:A',
        size='T 12"',
        weight=1,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d20(),
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon='Flail, Footman\'s, Holy Water Sprinkler (2H) [swivel end link (no chain) w/ attached 8" spiked mace]',
        weapon_type='P:SA',
        size='M 36" staff +8"',
        weight=12,
        weight_distribution=0.60,
        fulcrum_range='5-70',
        weapon_range=0,
        damage=d10()+d10()+d10()+3,
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon='Flail, Footman\'s Military (2H) [swivel end link (no chain) w/ attached 15" sectioned + spiked rod]',
        weapon_type='P:SA',
        size='M 36" staff +15"',
        weight=13,
        weight_distribution=0.60,
        fulcrum_range='5-70',
        weapon_range=0,
        damage=d12()+d12()+d12()+2,
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon="Flail, Horseman's (w/ chain and one spiked ball)",
        weapon_type='P:SA',
        size='S 24" staff +12"',
        weight=6,
        weight_distribution=0.80,
        fulcrum_range='10-60',
        weapon_range=0,
        damage=d10()+d10()+1,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon="Flail, Horseman's (w/ chains + two spiked balls)",
        weapon_type='P:SA',
        size='S 24" staff +12"',
        weight=7,
        weight_distribution=0.80,
        fulcrum_range='10-60',
        weapon_range=0,
        damage=d10()+d10()+3,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Garrote (2H) (thin wire for choking)',
        weapon_type='0:A',
        size='S 24"',
        weight=1,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d8()+d8()+d8(),
        l=0,
        m=0,
        h=-50,
    ),
    WeaponModel(
        weapon='Hammer, Maul (2H) (military sledge of stone)',
        weapon_type='P:S',
        size='M 36"',
        weight=10,
        weight_distribution=0.90,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d12()+d12()+d12()+d12()+4,
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon="Hammer, War, Footman's (2H) (with back spike)",
        weapon_type='P(S):SA',
        size='M 30-33"',
        weight=3,
        weight_distribution=0.70,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon="Hammer, War, Horseman's (with back spike) (also thrown)",
        weapon_type='P(S):SA',
        size='S 24"',
        weight=2,
        weight_distribution=0.80,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d20()+2,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Lance, Light (blunted end, hollow pole)',
        weapon_type='P:SA',
        size='L 60"',
        weight=5,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d12()+2,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Lance, Heavy (x2 charge)',
        weapon_type='S:SA',
        size='L 168"',
        weight=10,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d20()+3,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Lance, Jousting (x2 set charge) (blunted end)',
        weapon_type='P:SA',
        size='L 168"',
        weight=6,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d12()+3,
        l=0,
        m=0,
        h=0,
    ),
    WeaponModel(
        weapon="Mace, Footman's (2H)",
        weapon_type='P:SA',
        size='M 36"',
        weight=6,
        weight_distribution=0.85,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+3,
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon="Mace, Horseman's",
        weapon_type='P:SA',
        size='S 24"',
        weight=4,
        weight_distribution=0.90,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d20()+3,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Mace-axe (2H)',
        weapon_type='H/P:SA',
        size='M 36"',
        weight=7,
        weight_distribution=0.90,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+4,
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon='Morgenstern (Morningstar) (2H)',
        weapon_type='S/P:SA',
        size='M 48"',
        weight=8,
        weight_distribution=0.80,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+3,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon="Pick, Military, Footman's (2H) (also called the Bisacuta, Oucin, Besague)",
        weapon_type='H(S):SA',
        size='M 48"',
        weight=6,
        weight_distribution=0.85,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+3,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon="Pick, Military, Horseman's",
        weapon_type='H(S):SA',
        size='S 24"',
        weight=4,
        weight_distribution=0.80,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d20()+3,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Polearm, Awl Pike (2H) (x2 set charge)',
        weapon_type='S:SA',
        size='L 216-264"',
        weight=12,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10()+2,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Polearm, Berdeesh (2H) (Bardiche or Sparth Axe)',
        weapon_type='H:SA',
        size='L 60"',
        weight=7,
        weight_distribution=0.85,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+3,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon="Polearm, Bec de Corbin (Raven's Beak) (2H)",
        weapon_type='S/P:SA',
        size='L 72"',
        weight=6,
        weight_distribution=0.80,
        fulcrum_range='0/5-90',
        weapon_range=0,
        damage=d12()+d12()+1,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Bill (2H)',
        weapon_type='S/H:SA',
        size='L >95"',
        weight=10,
        weight_distribution=0.85,
        fulcrum_range='0/5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Polearm, Bipennis (2H) (double-bladed Poleaxe)',
        weapon_type='H:SA',
        size='L 72"',
        weight=12,
        weight_distribution=0.90,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d12()+d12()+d12()+2,
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Fauchard (2H)',
        weapon_type='H:SA',
        size='L >95"',
        weight=7,
        weight_distribution=0.75,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=0,
        h=-15,
    ),
    WeaponModel(
        weapon='Polearm, Glaive (2H)',
        weapon_type='H:SA',
        size='L >95"',
        weight=8,
        weight_distribution=0.80,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Polearm, Guisarme (2H)',
        weapon_type='H:SA',
        size='L >71"',
        weight=8,
        weight_distribution=0.75,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Halberd (2H) (x2 set charge)',
        weapon_type='S/H:SA',
        size='L 60-96"',
        weight=10,
        weight_distribution=0.85,
        fulcrum_range='0/5-90',
        weapon_range=0,
        damage=d12()+d12()+d12()+1,
        l=0,
        m=-5,
        h=-5,
    ),
    WeaponModel(
        weapon='Polearm, Military Fork (2H) (x2 set charge)',
        weapon_type='S:SA',
        size='L >83"',
        weight=7,
        weight_distribution=0.80,
        fulcrum_range='0',
        weapon_range=0,
        damage=d12()+d12(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Partisan (2H) (x2 set charge)',
        weapon_type='S:SA',
        size='L >83"',
        weight=8,
        weight_distribution=0.75,
        fulcrum_range='0',
        weapon_range=0,
        damage=d12()+d12(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Polearm, Poleaxe (single-bladed Bipennis w/spikes on back and tip) (2H)',
        weapon_type='S/H:SA',
        size='L 60-72"',
        weight=10,
        weight_distribution=0.85,
        fulcrum_range='0/5-90',
        weapon_range=0,
        damage=d12()+d12()+d12(),
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Ranseur (2H) (x2 set charge)',
        weapon_type='S:SA',
        size='L >95"',
        weight=7,
        weight_distribution=0.75,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10()+1,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Spetum (2H) (x2 set charge)',
        weapon_type='S:SA',
        size='L >95"',
        weight=7,
        weight_distribution=0.75,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10()+1,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Polearm, Voulge (2H) (Lochaber axe)',
        weapon_type='H:SA',
        size='L >95"',
        weight=10,
        weight_distribution=0.85,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Quarterstaff (iron end-caps)',
        weapon_type='P:SA',
        size='L 60-72"',
        weight=3,
        weight_distribution=0.50,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d10(),
        l=0,
        m=-20,
        h=-80,
    ),
    WeaponModel(
        weapon='Sap',
        weapon_type='P:SA',
        size='T 12"',
        weight=3,
        weight_distribution=0.90,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-5,
        h=-50,
    ),
    WeaponModel(
        weapon='Spear, Long (2H) (x2 set charge)',
        weapon_type='S:SA',
        size='L <156"',
        weight=5,
        weight_distribution=0.90,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Spear, Medium (also thrown)',
        weapon_type='S:SA',
        size='L 48-84"',
        weight=3,
        weight_distribution=0.85,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Spear, Short (half-spear or guard spear)',
        weapon_type='S:SA',
        size='S 27"',
        weight=3,
        weight_distribution=0.80,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Spear, Trident (2H)',
        weapon_type='S:SA',
        size='M 48-96"',
        weight=6,
        weight_distribution=0.80,
        fulcrum_range='0',
        weapon_range=0,
        damage=d6()+d6()+d6(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Strike, Unarmed (see Brawling skill)',
        weapon_type='P:A',
        size='0',
        weight=0,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=0,
        l=0,
        m=-50,
        h=-90,
    ),
    WeaponModel(
        weapon='Sword, Bastard (Hand-and-a-Half)',
        weapon_type='H:SA',
        size='L 43-51"',
        weight=7,
        weight_distribution=0.25,
        fulcrum_range='5-15',
        weapon_range=0,
        damage=d12()+d12()+d12()+1,
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Sword, Broadsword (seemingly, the average of swords)',
        weapon_type='H:SA',
        size='M 34-46"',
        weight=3,
        weight_distribution=0.40,
        fulcrum_range='5',
        weapon_range=0,
        damage=d12()+d12(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Sword, Cut + Thrust (thick sword of medium length)',
        weapon_type='S/H:SA',
        size='M 37-40"',
        weight=4,
        weight_distribution=0.30,
        fulcrum_range='0/10',
        weapon_range=0,
        damage=d12()+d12(),
        l=0,
        m=0,
        h=-15,
    ),
    WeaponModel(
        weapon='Sword, Falchion (curved blade, weighted end, single edge)',
        weapon_type='H:SA',
        size='S 28-30"',
        weight=4,
        weight_distribution=0.50,
        fulcrum_range='10',
        weapon_range=0,
        damage=d6()+d6()+d6(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Sword, Flamberge (2H) (wavy blade)',
        weapon_type='S:SA',
        size='L 48-64"',
        weight=10,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d10()+d10()+d10(),
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon='Sword, Gladius',
        weapon_type='S/H:SA',
        size='S 28"',
        weight=3,
        weight_distribution=0.20,
        fulcrum_range='0/10',
        weapon_range=0,
        damage=d8()+d8()+d8()+d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Sword, Long (thin blade that is long for a one-handed sword)',
        weapon_type='S:SA',
        size='M 34-42"',
        weight=4,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d20(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon="Sword, Short (sometimes called an Archer's sword)",
        weapon_type='S:SA',
        size='S 22-31"',
        weight=3,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d6()+d6()+d6(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Sword, Zweihander (2H)',
        weapon_type='S/H:S',
        size='L 58-75"',
        weight=15,
        weight_distribution=0.35,
        fulcrum_range='0/5-30',
        weapon_range=0,
        damage=d12()+d12()+d12()+d12(),
        l=0,
        m=0,
        h=-10,
    ),
    WeaponModel(
        weapon='Whip (subdual damage)',
        weapon_type='H:A',
        size='M 96"',
        weight=2,
        weight_distribution=0.15,
        fulcrum_range='5',
        weapon_range=0,
        damage=d4(),
        l=0,
        m=-80,
        h=-95,
    ),
    WeaponModel(
        weapon='Whip, Bull',
        weapon_type='H:A',
        size='L 168"',
        weight=3,
        weight_distribution=0.10,
        fulcrum_range='5',
        weapon_range=0,
        damage=d6(),
        l=0,
        m=-70,
        h=-90,
    ),
    WeaponModel(
        weapon='Whip, Cat-o-nine tails (subdual damage)',
        weapon_type='H:A',
        size='T 18"',
        weight=1,
        weight_distribution=0.20,
        fulcrum_range='5',
        weapon_range=0,
        damage=1,
        l=0,
        m=-80,
        h=-95,
    ),
    WeaponModel(
        weapon='Whip, Scourge (a Cat-o-nine tails with barbs)',
        weapon_type='H:A',
        size='T 18"',
        weight=1,
        weight_distribution=0.25,
        fulcrum_range='5',
        weapon_range=0,
        damage=d6(),
        l=0,
        m=-75,
        h=-90,
    ),
    WeaponModel(
        weapon='Axe, Hand (Hatchet)',
        weapon_type='H:A',
        size='T 15"',
        weight=2,
        weight_distribution=0.85,
        fulcrum_range='10-90',
        weapon_range=-1,
        damage=d10(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Bottle (if broken, treat as a knife)',
        weapon_type='P:A',
        size='T 12"',
        weight=1,
        weight_distribution=0.75,
        fulcrum_range='20',
        weapon_range=-1,
        damage=d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Bucket',
        weapon_type='P:SA',
        size='T 15"',
        weight=2,
        weight_distribution=0.75,
        fulcrum_range='10',
        weapon_range=0,
        damage=d4(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Chain',
        weapon_type='P:SA',
        size='L 60"',
        weight=5,
        weight_distribution=0.50,
        fulcrum_range='5',
        weapon_range=0,
        damage=d6(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Chair (2H)',
        weapon_type='P:SA',
        size='M 36"',
        weight=3,
        weight_distribution=0.75,
        fulcrum_range='5-90',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Cleaver',
        weapon_type='H:A',
        size='T 12"',
        weight=2,
        weight_distribution=0.75,
        fulcrum_range='10',
        weapon_range=-1,
        damage=d10(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='File, Metal',
        weapon_type='P:A',
        size='T <12"',
        weight=1,
        weight_distribution=0.50,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d4(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Flail, Grain (wood joined by rope)',
        weapon_type='P:SA',
        size='S 30"',
        weight=2,
        weight_distribution=0.30,
        fulcrum_range='10-60',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Fork, Pitch (2H)',
        weapon_type='S:SA',
        size='L >83"',
        weight=6,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d6()+d6(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Fork, Serving',
        weapon_type='S:A',
        size='T 12"',
        weight=1,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d6(),
        l=0,
        m=-5,
        h=-25,
    ),
    WeaponModel(
        weapon='Gauntlet',
        weapon_type='P:SA',
        size='T <12"',
        weight=2,
        weight_distribution=0.50,
        fulcrum_range='0',
        weapon_range=0,
        damage=d4(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Hammer, Tool (w/o back spike)',
        weapon_type='P:A',
        size='T 15"',
        weight=2,
        weight_distribution=0.90,
        fulcrum_range='10-90',
        weapon_range=-1,
        damage=d10()+d10(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Hammer, Sledge (2H)',
        weapon_type='P:S',
        size='M 36"',
        weight=8,
        weight_distribution=0.90,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d20()+d20(),
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon='Hoe (2H)',
        weapon_type='H:SA',
        size='M 36-48"',
        weight=3,
        weight_distribution=0.75,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d6(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Hook, Grappling',
        weapon_type='S/P:SA',
        size='T 18"',
        weight=4,
        weight_distribution=0.75,
        fulcrum_range='10-70',
        weapon_range=-1,
        damage=d6(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Knife, Hunting or Tool (single edge)',
        weapon_type='S:A',
        size='T 8-13"',
        weight=1,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=-1,
        damage=d8(),
        l=0,
        m=-15,
        h=-25,
    ),
    WeaponModel(
        weapon='Mallet (all wood)',
        weapon_type='P:A',
        size='T 12"',
        weight=2,
        weight_distribution=0.80,
        fulcrum_range='10-75',
        weapon_range=0,
        damage=d4(),
        l=0,
        m=-5,
        h=-20,
    ),
    WeaponModel(
        weapon='Quill',
        weapon_type='S:A',
        size='T 12"',
        weight=0,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d2(),
        l=0,
        m=-30,
        h=-95,
    ),
    WeaponModel(
        weapon='Pan, Frying (Iron)',
        weapon_type='P:SA',
        size='S 18"',
        weight=4,
        weight_distribution=0.75,
        fulcrum_range='10',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Pry bar (Crowbar)',
        weapon_type='P:SA',
        size='T 18"',
        weight=3,
        weight_distribution=0.50,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Rolling Pin',
        weapon_type='P:SA',
        size='T 12"',
        weight=2,
        weight_distribution=0.60,
        fulcrum_range='10',
        weapon_range=0,
        damage=d4(),
        l=0,
        m=-5,
        h=-20,
    ),
    WeaponModel(
        weapon='Scissors',
        weapon_type='S:A',
        size='T <10"',
        weight=0.5,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=d6(),
        l=0,
        m=-5,
        h=-25,
    ),
    WeaponModel(
        weapon='Scythe (2H)',
        weapon_type='H(S):SA',
        size='L 60"',
        weight=5,
        weight_distribution=0.50,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d8()+d8(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Shield',
        weapon_type='P:SA',
        size='varies',
        weight=0,
        weight_distribution=0.50,
        fulcrum_range='50',
        weapon_range=0,
        damage=d2(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Shoe',
        weapon_type='P:A',
        size='T <12"',
        weight=0.5,
        weight_distribution=0.50,
        fulcrum_range='50',
        weapon_range=-1,
        damage=d2(),
        l=0,
        m=-5,
        h=-25,
    ),
    WeaponModel(
        weapon='Shoe, Horse',
        weapon_type='P:SA',
        size='T <8"',
        weight=2,
        weight_distribution=0.50,
        fulcrum_range='50',
        weapon_range=-1,
        damage=d4(),
        l=0,
        m=-5,
        h=-20,
    ),
    WeaponModel(
        weapon='Shovel (2H)',
        weapon_type='H/P:SA',
        size='M 36-48"',
        weight=4,
        weight_distribution=0.80,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Sickle',
        weapon_type='H(S):A',
        size='T 18"',
        weight=2,
        weight_distribution=0.40,
        fulcrum_range='10',
        weapon_range=0,
        damage=d12(),
        l=0,
        m=-15,
        h=-25,
    ),
    WeaponModel(
        weapon='Spade (2H)',
        weapon_type='H/P:SA',
        size='M 36-48"',
        weight=3,
        weight_distribution=0.85,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Targe (Spiked Shield)',
        weapon_type='S:SA',
        size='S 24"',
        weight=6,
        weight_distribution=0.50,
        fulcrum_range='50',
        weapon_range=0,
        damage=d8(),
        l=0,
        m=-5,
        h=-20,
    ),
    WeaponModel(
        weapon='Torch (a burning club)',
        weapon_type='P:SA',
        size='S 24"',
        weight=1,
        weight_distribution=0.55,
        fulcrum_range='10-90',
        weapon_range=0,
        damage=d10()+d10(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Arrows (12 w/quiver)',
        weapon_type='S:0',
        size='S 30"',
        weight=2,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=0,
        l=0,
        m=0,
        h=0,
    ),
    WeaponModel(
        weapon='Axe, Hand (Hatchet)',
        weapon_type='H:SA',
        size='T 15"',
        weight=2,
        weight_distribution=-1,
        fulcrum_range='20',
        weapon_range=-1,
        damage=d10(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Bolas',
        weapon_type='P:SA',
        size='S 24"',
        weight=2,
        weight_distribution=-2,
        fulcrum_range='20',
        weapon_range=-2,
        damage=d4()+d4()+d4(),
        l=0,
        m=-20,
        h=-90,
    ),
    WeaponModel(
        weapon='Bolts (20 w/ quiver)',
        weapon_type='S:0',
        size='T 18"',
        weight=3,
        weight_distribution=0,
        fulcrum_range='0',
        weapon_range=0,
        damage=0,
        l=0,
        m=0,
        h=0,
    ),
    WeaponModel(
        weapon='Boomerang (does not return to thrower)',
        weapon_type='P:A',
        size='T 18"',
        weight=1,
        weight_distribution=-2,
        fulcrum_range='10',
        weapon_range=-2,
        damage=d6(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Bottle (if broken, treat as a knife)',
        weapon_type='P:SA',
        size='T 12"',
        weight=1,
        weight_distribution=-1,
        fulcrum_range='10',
        weapon_range=-1,
        damage=d8(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Bottle, Oil (with ignited wick) (Molotov cocktail)',
        weapon_type='P:SA',
        size='T 12"',
        weight=2,
        weight_distribution=-1,
        fulcrum_range='20',
        weapon_range=-1,
        damage=floor(d20()/ d10()),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Bow, Short (2H) (can use mounted)',
        weapon_type='S:A',
        size='M 48"',
        weight=2,
        weight_distribution=0,
        fulcrum_range='20',
        weapon_range=60,
        damage=d12(),
        l=0,
        m=-20,
        h=-50,
    ),
    WeaponModel(
        weapon='Bow, Long (2H) (too big to use mounted)',
        weapon_type='S:A',
        size='L 66-79"',
        weight=3,
        weight_distribution=0,
        fulcrum_range='30',
        weapon_range=100,
        damage=d20(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Cleaver',
        weapon_type='H:SA',
        size='T 12"',
        weight=2,
        weight_distribution=-1,
        fulcrum_range='10',
        weapon_range=-1,
        damage=d10(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Crossbow, Hand (2H) (drawn by the hand) [Note: Crossbows and crossbowmen are also called arbalests + arbalestiers.]',
        weapon_type='S:A',
        size='M 36"',
        weight=7,
        weight_distribution=0,
        fulcrum_range='70',
        weapon_range=80,
        damage=d10()+d10()+1,
        l=0,
        m=0,
        h=-5,
    ),
    WeaponModel(
        weapon='Crossbow, Wheel + Ratchet (2H) (must be cranked) [Note: Crossbows and crossbowmen are also called arbalests + arbalestiers. 400 draw lbs. required.]',
        weapon_type='S:A',
        size='M 36"',
        weight=14,
        weight_distribution=0,
        fulcrum_range='100',
        weapon_range=120,
        damage=d10()+d10()+d10()+2,
        l=0,
        m=0,
        h=0,
    ),
    WeaponModel(
        weapon='Dagger (double-edged)',
        weapon_type='S:A',
        size='T 11-18"',
        weight=1,
        weight_distribution=-1,
        fulcrum_range='10',
        weapon_range=-1,
        damage=d10(),
        l=0,
        m=-5,
        h=-20,
    ),
    WeaponModel(
        weapon='Dart',
        weapon_type='S:A',
        size='T 18"',
        weight=0.5,
        weight_distribution=-2,
        fulcrum_range='5',
        weapon_range=-2,
        damage=d8(),
        l=0,
        m=-25,
        h=-75,
    ),
    WeaponModel(
        weapon='Flask',
        weapon_type='P:SA',
        size='T 72"',
        weight=1,
        weight_distribution=-1,
        fulcrum_range='10',
        weapon_range=-1,
        damage=d4(),
        l=0,
        m=-10,
        h=-25,
    ),
    WeaponModel(
        weapon='Flask, Oil (with ignited wick)',
        weapon_type='P:SA',
        size='T 72"',
        weight=1,
        weight_distribution=-1,
        fulcrum_range='10',
        weapon_range=-1,
        damage=floor(d8()/ d4()),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Hammer, Tool (w/o back spike)',
        weapon_type='P:SA',
        size='T 15"',
        weight=2,
        weight_distribution=-1,
        fulcrum_range='20',
        weapon_range=-1,
        damage=d12(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon="Hammer, War, Horseman's (with back spike)",
        weapon_type='P(S):SA',
        size='S 24"',
        weight=2,
        weight_distribution=-1,
        fulcrum_range='20',
        weapon_range=-1,
        damage=d20()+2,
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Hook, Grappling',
        weapon_type='S/P:SA',
        size='T 18"',
        weight=4,
        weight_distribution=-1,
        fulcrum_range='40',
        weapon_range=-1,
        damage=d6(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Hudbat (all metal hand ax)',
        weapon_type='H(S):SA',
        size='S 22"',
        weight=4,
        weight_distribution=-1,
        fulcrum_range='40',
        weapon_range=-1,
        damage=d20(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Javelin',
        weapon_type='S:SA',
        size='M 60"',
        weight=2,
        weight_distribution=-3,
        fulcrum_range='20',
        weapon_range=-3,
        damage=d12(),
        l=0,
        m=-10,
        h=-25,
    ),
    WeaponModel(
        weapon='Knife, Hunting or Tool (single edge)',
        weapon_type='S:A',
        size='T 8-12"',
        weight=1,
        weight_distribution=-1,
        fulcrum_range='10',
        weapon_range=-1,
        damage=d8(),
        l=0,
        m=-15,
        h=-25,
    ),
    WeaponModel(
        weapon='Knife, Throwing (double-edged)',
        weapon_type='S:A',
        size='T <8"',
        weight=0.5,
        weight_distribution=-2,
        fulcrum_range='5',
        weapon_range=-2,
        damage=d6(),
        l=0,
        m=-10,
        h=-20,
    ),
    WeaponModel(
        weapon='Net, Weighted',
        weapon_type='P:SA',
        size='L 120"',
        weight=10,
        weight_distribution=-1,
        fulcrum_range='100',
        weapon_range=-1,
        damage=0,
        l=0,
        m=0,
        h=0,
    ),
    WeaponModel(
        weapon='Pilum',
        weapon_type='S:SA',
        size='L 72-84"',
        weight=1,
        weight_distribution=-3,
        fulcrum_range='10',
        weapon_range=-3,
        damage=d12(),
        l=0,
        m=-5,
        h=-10,
    ),
    WeaponModel(
        weapon='Rock',
        weapon_type='P:A',
        size='T 3"',
        weight=1,
        weight_distribution=-3,
        fulcrum_range='10',
        weapon_range=-3,
        damage=d8(),
        l=0,
        m=-5,
        h=-25,
    ),
    WeaponModel(
        weapon='Sling (2H)',
        weapon_type='P:SA',
        size='S 24-36"',
        weight=1,
        weight_distribution=-4,
        fulcrum_range='5',
        weapon_range=-4,
        damage=d8()+1,
        l=0,
        m=-5,
        h=-25,
    ),
    WeaponModel(
        weapon='Spear, Medium',
        weapon_type='S:SA',
        size='L 60-84"',
        weight=3,
        weight_distribution=-2,
        fulcrum_range='30',
        weapon_range=-2,
        damage=d10()+d10(),
        l=0,
        m=-5,
        h=-15,
    ),
    WeaponModel(
        weapon='Vial',
        weapon_type='P:SA',
        size='T 4"',
        weight=0.5,
        weight_distribution=-2,
        fulcrum_range='5',
        weapon_range=-2,
        damage=d4(),
        l=0,
        m=-10,
        h=-50,
    ),
]
